workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_CERTIFICATE_PASSWORD: Envie pela interface do Codemagic
        APPLE_PROVISIONING_PROFILE_NAME: Envie pela interface do Codemagic
    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      certificate_url: Envie pela interface do Codemagic
      certificate_password: $APPLE_CERTIFICATE_PASSWORD
      provisioning_profile_url: Envie pela interface do Codemagic
      signing_identity: Apple Distribution
      provisioning_profile_name: $APPLE_PROVISIONING_PROFILE_NAME
workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_CERTIFICATE_PASSWORD: Envie pela interface do Codemagic
        APPLE_PROVISIONING_PROFILE_NAME: Envie pela interface do Codemagic
    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      certificate_url: Envie pela interface do Codemagic
      certificate_password: $APPLE_CERTIFICATE_PASSWORD
      provisioning_profile_url: Envie pela interface do Codemagic
      signing_identity: Apple Distribution
      provisioning_profile_name: $APPLE_PROVISIONING_PROFILE_NAME
