workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_CERTIFICATE_PASSWORD: $APPLE_CERTIFICATE_PASSWORD
        APPLE_PROVISIONING_PROFILE_NAME: $APPLE_PROVISIONING_PROFILE_NAME
    scripts:
      - name: Instalar dependências
        script: flutter pub get
      - name: Verificar código
        script: flutter analyze
      - name: Testes unitários
        script: flutter test
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa

  android-release:
    name: Android Release Build
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Instalar dependências
        script: flutter pub get
      - name: Verificar código
        script: flutter analyze
      - name: Testes unitários
        script: flutter test
      - name: Build Android (.aab)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
